import type { Metadata } from "next";
import "../globals.css";

import ClientLayoutShell from "./ClientLayoutShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body>
        <ClientLayoutShell modal={modal}>{children}</ClientLayoutShell>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import React from "react";
// import "../globals.css";
// import { Header } from "@/shared/components/shared/index";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function HomeLayout({
//   children,
//   modal,
// }: Readonly<{
//   children: React.ReactNode;
//   modal?: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <Header />
//         {children}
//         {modal}
//       </body>
//     </html>
//   );
// }
