import { Header } from "@/shared/components/shared";
import { Metadata } from "next";

export const netadata: Metadata = {
  title: "Next.js | Корзина",
  description: "Generated by Next.js",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#F4F1EE]">
      <Header hasSearch={false} hasCart={false} className="border-gray-20" />
      {children}
    </main>
  );
}
